### ISSUE TITLE
Feature request: disable Windows key

### ISSUE THREAD

**Issue by Vortigern** [ccMSC/ckb#142] opened 2015-10-15 11:03 UTC
Hi there,
I would like to ask for a new feature: the ability to save the status of the "Windows key" lock button. In such manner you don't have to push it at each reboot.
Obviously, by saving the status users who need the "Windows keys" may leave them enabled.

Thanks,
Alessio

**Comment by ccMSC** [comment] 2015-10-25 08:59
Whoops, thought I replied to this earlier. Sorry about that!

Anyway, what you describe was actually the intended behavior. Seems it got dropped at some point. As of a4cf26baadce6a3db4127a94ece0ea4da79027c0 it should be fixed again.

**Closed** 2015-11-11 07:44 UTC
