### ISSUE TITLE
Scimitar RGB not connecting 

### ISSUE THREAD

**Issue by tjw0lf** [ccMSC/ckb#254] opened 2016-02-19 02:50 UTC
If you can help on why not connecting please

Would love for it to work

I'm on corsairs forum @ImtheBest

**Comment by ccMSC** [comment] 2016-02-20 10:09
There's an issue with the firmware right now. I'm trying to get it fixed soon.

**Comment by ccMSC** [comment] 2016-03-14 02:12
Sorry, I should have closed this earlier as a duplicate of #243. Potential solution is posted in that thread, try it out and let me know if it's working for you.

**Closed by ccMSC** 2016-03-14 02:12 UTC

**Comment by tjw0lf** [comment] 2016-03-29 23:46
Please don't close this without letting me know first please. 
What are the step and everything i have to do? Where is it Installation steps
Please thank you

**Comment by ccMSC** [comment] 2016-03-31 07:41
If you're on OSX, I provided a link to an installer which supports the new firmware: https://dl.dropboxusercontent.com/u/16424004/ckb/ckb%20v0.2.4%2Bf02.pkg

On Linux, download the `fw2` branch (zip link: https://github.com/ccMSC/ckb/archive/fw2.zip ) and follow the installation as normal.

**Comment by CMasterson** [comment] 2016-03-31 14:17
New installer fixed the issue for me, thanks!

**Comment by tjw0lf** [comment] 2016-03-31 17:34
Sorry i should have stated I'm running Linux. Not OS X or nothing like that no MAC guy here. And where can i find the fw2 for future references
